sudo: enabled

language: generic

git:
  depth: 10

addons:
  apt:
    sources:
      - 'ubuntu-toolchain-r-test'
    packages:
      - 'xvfb'
      - 'libgirepository1.0-dev'
      - 'gobject-introspection'
      - 'build-essential'
      - 'g++-8'
      - 'gtk+3.0'
      - 'libgtk-3-dev'
      - 'gir1.2-gtk-3.0'
      - 'libsoup2.4'
      - 'gir1.2-soup-2.4'

matrix:
  include:
     # Linux
     - os: linux
       dist: trusty
       env: NODE_VERSION="10" CC="gcc-8" CXX="g++-8"
     - os: linux
       dist: trusty
       env: NODE_VERSION="9" CC="gcc-8" CXX="g++-8"
     - os: linux
       dist: trusty
       env: NODE_VERSION="8" CC="gcc-8" CXX="g++-8"
     - os: linux
       dist: trusty
       env: NODE_VERSION="7" CC="gcc-8" CXX="g++-8"

     # OS X
     - os: osx
       compiler: clang
       env: NODE_VERSION="10" # node abi 64
     - os: osx
       compiler: clang
       env: NODE_VERSION="9" # node abi 59
     - os: osx
       compiler: clang
       env: NODE_VERSION="8" # node abi 57
     - os: osx
       compiler: clang
       env: NODE_VERSION="7" # node abi 51


env:
  global:
    - JOBS: "8"
    - secure: dy/dUI0u1hLQvce4WwnG0t2aCoa3pMNZAPOMRj3mZF0a1HJSBAsvtLoH1T4y2YxiT7uevENTkkgBV26Nx+CHsRT1I6LJAZ8mr4dM9zWRCvmDc6DUleyZ1mVTKIs+aTsr5VW8SgWK83qWQU508Wbc16CChF9CuIUJ0/pJ3rIePBPFZIShkwB5r6oLN/7Xbu0wsbnVQTj+3fyzc+ZNos6RqSpWRw6mJJtmkViMntPbNkrt3veCwNOHLj9nbuQnM29exgReHNrHNp+rE5wWLIPogYs2oKPVqNDjr/iPPd6+kSUAnfUuLR6pFU8+544EPACedVK6nCZ9hiZSqJXjTghA46JQ26mLTcgwA1Oj6Bs1VG8a0rU7NZsz3bT9cMR0K8WRClnJg9fQgrwPd7IZPm0cZELNKOpYmUE06sB3MFSoZFLVE4FaFzF53V9zuGwFIMASFeANjTOinZkiKcfvbTn1FOnI+5KbT4oZCDrERzTyjC2cNtKvhsk990rPLC/Bf0QBR4j31oxGtXP1sGcjhfCpfozlYkCnzZ2iLWuZ2jkWldFBMZos6/ucMKGtofbva/3VehD9/KtFB/2fDrOpUxak94Uvg8TciCYCveHb+prdlpn++eQIdU/7gSsuaaPmwEl+fBngIxBdFiHN2oFDDQltR/qt3AQuBbTn902oEpAv5H4=
    - secure: CltWItR/J4IBpP2ZkGN36qQGlLkNTewsz+c1YmCF0HsVcUW/7o57YaOLrsPI8tyOm9W7gZZntAzjptGr9wL9xzp/SMPE8ARQ7cXTw/WcuGkFT7rh/dYbnDCTB7QcJUs75EYBQYFmn4AXaIWT0MIcJ4nGsPjWltExLI9ShbxaCSLMZWn0rDLwg/sibJeRK2XW2BggoJBM5jB7juO2HIfwcnXkM43wP9xcARY9VsRtCJfw8mqgsHRyKs451Zn1TvROvEJQ0uD3mdtAZobhN1OTrf6wHGqG5ESX4ouk63IEN55Ap+Pw9JevYazAPsa1pCzru551KoTnV62vE9C2CHoAvBNV8Jl8eiMwpcljXDvjtaMIBbg5dhEsDP1TFtF+OXBvm638WurqbXUzEL5ZcUK+Y1Hr6e7hwLbB1wL0pCcD0oUpOCJXxcI/aELRGklEOUPfv23fg4PLrml3cFxHk3YdcB7M2AEZwwsQgoFdKOE9X9sN/bVTOwxJ55gXcQDCyP+9dm15Yssl8DbmmbrBFABisM6kIwgFhC0q3rbd6qfY6bv/0q3Ei1W+42hwOYnDSkJCwRvaOUTHyHJykHE5EvWdqu81JRCMCFdNd0DdsDsCEiigXu5GM8s17IWekZr+t6oE7vc9D0DJDIZA9K+krU0RzA8UKiDYyI0V723gZwnKHGI=

before_install:
- source ./scripts/install_node.sh ${NODE_VERSION}

install:
# put node-pre-gyp on path
- export PATH=./node_modules/.bin/:$PATH
- if [[ $(uname -s) == 'Darwin' ]]; then
    brew install git node gtk+3 gobject-introspection glib libsoup;
    clang --version;
  fi;

before_script:
# get commit message
- export COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')

script:
- ./scripts/build.sh
